services:
  db:
    image: postgres:14
    container_name: shortener_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432

volumes:
  db-data:
