services:
  db:
    image: postgres:14
    container_name: shortener_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
  shortener:
    build: .
    container_name: url_shortener
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8001:8001
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
